name: build pages

on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python3 deploy.py
      - name: Commit files
        run: |
          cd dist
          git config --global user.email "29306733+oldshensheep@users.noreply.github.com "
          git config --global user.name "oldshensheep"
          git init
          git add -A
          git commit -m 'deploy'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          directory: dist
          force: true

